/**
 * Created on 28 Feb 2023 by lonmee
 *
 */
const IDENTITY_CREATE = 'CREATE',
  IDENTITY_USE = 'USE',
  IDENTITY_MIGRATE = 'MIGRATE',
  IDENTITY_RESTORE = 'RESTORE',
  IDENTITY_CLEAR = 'CLEAR';
export {
  IDENTITY_CREATE,
  IDENTITY_USE,
  IDENTITY_MIGRATE,
  IDENTITY_RESTORE,
  IDENTITY_CLEAR,
};
